import { Job } from '../../types';

// Helper to generate dynamic recent dates
const now = Date.now();
const hoursAgo = (h: number) => new Date(now - h * 60 * 60 * 1000).toISOString();
const daysAgo = (d: number) => new Date(now - d * 24 * 60 * 60 * 1000).toISOString();

export const SEED_JOBS: Job[] = [
  {
    id: 'job_razorpay_01',
    source: 'direct',
    sourceJobId: 'rzp-rn-9821',
    title: 'Senior React Native Developer',
    company: 'Razorpay',
    companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=60',
    companyDomain: 'razorpay.com',
    location: 'Ahmedabad, India (Hybrid)',
    description: 'We are looking for a Senior React Native Engineer to lead the mobile checkout experience for millions of merchants and end users across India and SEA. You will design, build, and optimize high-throughput, low-latency mobile payment flows.',
    requirements: [
      '4+ years of professional software engineering with 3+ years in React Native',
      'Strong proficiency in TypeScript, Redux Toolkit, and native Android/iOS bridging',
      'Proven experience reducing app bundle size and optimizing 60fps animations',
      'Solid understanding of security best practices in Fintech and tokenization',
      'Experience with CI/CD pipelines using Fastlane and GitHub Actions',
    ],
    benefits: [
      'Comprehensive health insurance including mental wellness support',
      'Flexible hybrid work policy with home office reimbursement',
      'Annual learning & development stipend of ₹50,000',
      'Generous ESOP stock options and bi-annual performance appraisals',
    ],
    salaryMin: 1800000,
    salaryMax: 2800000,
    currency: 'INR',
    employmentType: 'full-time',
    remoteType: 'hybrid',
    skills: ['React Native', 'TypeScript', 'Redux', 'iOS', 'Android', 'Mobile Performance'],
    experienceLevel: 'Senior',
    postedAt: hoursAgo(2),
    applyUrl: 'https://razorpay.com/careers/mobile-lead',
    applicationType: 'direct',
    isActive: true,
  },
  {
    id: 'job_linear_02',
    source: 'lever',
    sourceJobId: 'lev-linear-432',
    title: 'Full Stack Engineer (React + Node.js)',
    company: 'Linear',
    companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=60',
    companyDomain: 'linear.app',
    location: 'Remote (Worldwide)',
    description: 'Linear is building the future of software development tracking. We are seeking a Product Engineer to craft blazing fast web experiences with React, TypeScript, GraphQL, and distributed backend sync engines.',
    requirements: [
      '3+ years building high-performance web applications in React and TypeScript',
      'Experience with offline-first state synchronization and WebSockets',
      'Strong eye for UI/UX details, micro-interactions, and keyboard ergonomics',
      'Familiarity with Node.js, PostgreSQL, and Redis',
    ],
    benefits: [
      '100% remote team with asynchronous culture',
      'Competitive global equity grant & USD compensation',
      '$4,000 initial remote home office setup budget',
      'Unlimited paid time off (minimum 4 weeks recommended)',
    ],
    salaryMin: 3200000,
    salaryMax: 4800000,
    currency: 'INR',
    employmentType: 'full-time',
    remoteType: 'remote',
    skills: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'GraphQL', 'Tailwind CSS'],
    experienceLevel: 'Mid-Level',
    postedAt: hoursAgo(5),
    applyUrl: 'https://jobs.lever.co/linear/fullstack-eng',
    applicationType: 'external',
    isActive: true,
  },
  {
    id: 'job_swiggy_03',
    source: 'greenhouse',
    sourceJobId: 'gh-swiggy-849',
    title: 'Frontend Platform Engineer (React / Next.js)',
    company: 'Swiggy',
    companyLogo: 'https://images.unsplash.com/photo-1555421689-491a97ff2040?w=100&auto=format&fit=crop&q=60',
    companyDomain: 'swiggy.com',
    location: 'Bangalore, India',
    description: 'Join the Core Web team powering Instamart and Food delivery web surfaces. You will lead Next.js SSR performance, core web vitals optimization, and modular design systems.',
    requirements: [
      '3 to 6 years of expertise with React, Next.js, and modern browser APIs',
      'Deep understanding of Webpack/Vite module federation and bundle splitting',
      'Experience authoring shared NPM component libraries and design tokens',
      'Knowledge of Core Web Vitals (LCP, FID, CLS) optimization techniques',
    ],
    benefits: [
      'Relocation assistance to Bangalore + initial hotel stay',
      'Subsidized meal coupons & high-speed home internet reimbursement',
      'Annual wellness bonus & medical insurance for family',
    ],
    salaryMin: 2200000,
    salaryMax: 3400000,
    currency: 'INR',
    employmentType: 'full-time',
    remoteType: 'hybrid',
    skills: ['React', 'Next.js', 'TypeScript', 'Design Systems', 'Performance Optimization', 'Webpack'],
    experienceLevel: 'Senior',
    postedAt: hoursAgo(18),
    applyUrl: 'https://boards.greenhouse.io/swiggy/jobs/frontend-platform',
    applicationType: 'external',
    isActive: true,
  },
  {
    id: 'job_zepto_04',
    source: 'adzuna',
    sourceJobId: 'adz-zepto-771',
    title: 'MERN Stack Developer (Quick Commerce)',
    company: 'Zepto',
    companyLogo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=100&auto=format&fit=crop&q=60',
    companyDomain: 'zeptonow.com',
    location: 'Ahmedabad / Remote',
    description: 'Zepto is transforming quick commerce in India. We are hiring a MERN Stack Developer to build hyper-local dispatch dashboards, rider tracking portals, and inventory management web apps.',
    requirements: [
      '2+ years working with MongoDB, Express, React, and Node.js',
      'Strong grasp of RESTful API design, indexing in MongoDB, and Redis caching',
      'Experience with Tailwind CSS and responsive admin dashboards',
      'Ability to write clean, unit-tested code with Jest/React Testing Library',
    ],
    benefits: [
      'Fast-paced hypergrowth startup experience',
      'Competitive salary + annual retention bonus',
      'Health coverage + accident insurance',
    ],
    salaryMin: 1200000,
    salaryMax: 1800000,
    currency: 'INR',
    employmentType: 'full-time',
    remoteType: 'remote',
    skills: ['React', 'Node.js', 'MongoDB', 'Express', 'JavaScript', 'Redis'],
    experienceLevel: 'Mid-Level',
    postedAt: daysAgo(1),
    applyUrl: 'https://zepto.freshteam.com/jobs/mern-dev',
    applicationType: 'external',
    isActive: true,
  },
  {
    id: 'job_stripe_05',
    source: 'direct',
    sourceJobId: 'strp-dev-9102',
    title: 'Staff Backend & Cloud Engineer (Python / AWS)',
    company: 'Stripe',
    companyLogo: 'https://images.unsplash.com/photo-1579389083078-4e7018379f7e?w=100&auto=format&fit=crop&q=60',
    companyDomain: 'stripe.com',
    location: 'Remote (India / APAC)',
    description: 'Help build Stripe global financial infrastructure. You will design resilient distributed transaction systems handling billions in annual payment volume.',
    requirements: [
      '6+ years developing high-scale cloud backend services',
      'Deep fluency in Python, Go, or Java, alongside PostgreSQL and AWS',
      'Experience with distributed systems consistency, queues (Kafka/SQS), and idempotent APIs',
      'Passionate about system architecture, reliability, and security',
    ],
    benefits: [
      'Industry-leading compensation & Tier-1 global equity package',
      '$5,000 annual continuous education and conference allowance',
      'Comprehensive private health coverage for employee + parents/dependents',
    ],
    salaryMin: 4500000,
    salaryMax: 7000000,
    currency: 'INR',
    employmentType: 'full-time',
    remoteType: 'remote',
    skills: ['Python', 'AWS', 'PostgreSQL', 'Docker', 'Distributed Systems', 'Kafka'],
    experienceLevel: 'Lead',
    postedAt: daysAgo(1),
    applyUrl: 'https://stripe.com/jobs/listing/staff-cloud-engineer',
    applicationType: 'direct',
    isActive: true,
  },
  {
    id: 'job_zerodha_06',
    source: 'direct',
    sourceJobId: 'zrd-sys-101',
    title: 'Systems & Web Developer (Python / Go / Vue / React)',
    company: 'Zerodha',
    companyLogo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=100&auto=format&fit=crop&q=60',
    companyDomain: 'zerodha.com',
    location: 'Bangalore, India (On-site / Hybrid)',
    description: 'Work at India’s largest stock broker. We write clean, minimalist, bloat-free software that powers Kite, Console, and Coin for over 10 million active traders.',
    requirements: [
      'Strong foundational computer science concepts (networking, concurrency, memory)',
      'Proficiency in Python and/or Go, plus modern JavaScript/TypeScript',
      'No BS, practical engineering approach with attention to simplicity',
      'Experience with PostgreSQL, Linux system administration, and Websockets',
    ],
    benefits: [
      'No micromanagement, high autonomy engineering culture',
      'Profit sharing bonus scheme',
      'Top-tier medical coverage and fitness stipends',
    ],
    salaryMin: 2000000,
    salaryMax: 3500000,
    currency: 'INR',
    employmentType: 'full-time',
    remoteType: 'hybrid',
    skills: ['Python', 'Go', 'React', 'PostgreSQL', 'Linux', 'WebSockets'],
    experienceLevel: 'Mid-Level',
    postedAt: daysAgo(2),
    applyUrl: 'https://zerodha.com/careers/systems-web',
    applicationType: 'direct',
    isActive: true,
  },
  {
    id: 'job_datadog_07',
    source: 'lever',
    sourceJobId: 'lev-dd-291',
    title: 'Senior Frontend Engineer - Observability Dashboards',
    company: 'Datadog',
    companyLogo: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=100&auto=format&fit=crop&q=60',
    companyDomain: 'datadoghq.com',
    location: 'Remote',
    description: 'Create ultra-responsive real-time metric visualization dashboards. You will work with WebGL, Canvas, and React to render millions of live time-series data points seamlessly.',
    requirements: [
      '5+ years building complex web dashboards in React & TypeScript',
      'Experience with D3.js, WebGL, or Canvas rendering algorithms',
      'Expertise in optimizing browser memory footprints and DOM tree rendering',
    ],
    benefits: [
      'Global remote compensation with attractive RSU stock grants',
      'Home ergonomics allowance + latest Apple MacBook Pro',
      'Paid sabbatical leave after 4 years of service',
    ],
    salaryMin: 3800000,
    salaryMax: 5500000,
    currency: 'INR',
    employmentType: 'full-time',
    remoteType: 'remote',
    skills: ['React', 'TypeScript', 'D3.js', 'WebGL', 'Performance Optimization', 'CSS'],
    experienceLevel: 'Senior',
    postedAt: daysAgo(3),
    applyUrl: 'https://jobs.lever.co/datadog/senior-frontend-dashboards',
    applicationType: 'external',
    isActive: true,
  },
  {
    id: 'job_hashicorp_08',
    source: 'greenhouse',
    sourceJobId: 'gh-hashi-519',
    title: 'DevOps & Cloud Infrastructure Engineer',
    company: 'HashiCorp',
    companyLogo: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=100&auto=format&fit=crop&q=60',
    companyDomain: 'hashicorp.com',
    location: 'Remote',
    description: 'Automate multi-cloud deployments across AWS and Azure using Terraform, Nomad, and Vault. You will be responsible for zero-downtime releases and infrastructure as code.',
    requirements: [
      '4+ years managing production Kubernetes and Terraform infrastructure',
      'Deep familiarity with AWS/GCP IAM, VPC networking, and security governance',
      'Proficiency in writing automation scripts in Go or Python',
      'Experience building CI/CD pipelines with GitHub Actions and ArgoCD',
    ],
    benefits: [
      'Remote-first global workforce with flexible hours',
      'Wellness stipend, parental leave, and generous 401k/PF matching',
    ],
    salaryMin: 2800000,
    salaryMax: 4200000,
    currency: 'INR',
    employmentType: 'full-time',
    remoteType: 'remote',
    skills: ['AWS', 'Docker', 'Kubernetes', 'Terraform', 'CI/CD', 'Python'],
    experienceLevel: 'Senior',
    postedAt: daysAgo(4),
    applyUrl: 'https://boards.greenhouse.io/hashicorp/jobs/devops-infra',
    applicationType: 'external',
    isActive: true,
  },
  {
    id: 'job_postman_09',
    source: 'adzuna',
    sourceJobId: 'adz-postman-332',
    title: 'React Native & Desktop App Developer',
    company: 'Postman',
    companyLogo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=100&auto=format&fit=crop&q=60',
    companyDomain: 'postman.com',
    location: 'Ahmedabad / Bangalore',
    description: 'Postman is used by over 25 million developers globally. Build rich API client interactions across React, Electron, and React Native platforms.',
    requirements: [
      '3+ years experience with React, TypeScript, and Electron or React Native',
      'Deep understanding of HTTP protocols, WebSockets, gRPC, and REST specs',
      'Familiarity with state management libraries and native bindings',
    ],
    benefits: [
      'Annual learning allowance',
      'Hybrid work model with flexible timings',
      'Comprehensive group insurance',
    ],
    salaryMin: 1800000,
    salaryMax: 2600000,
    currency: 'INR',
    employmentType: 'full-time',
    remoteType: 'hybrid',
    skills: ['React Native', 'React', 'TypeScript', 'Node.js', 'API Design'],
    experienceLevel: 'Mid-Level',
    postedAt: daysAgo(5),
    applyUrl: 'https://postman.com/careers/mobile-desktop',
    applicationType: 'external',
    isActive: true,
  },
  {
    id: 'job_airbnb_10',
    source: 'direct',
    sourceJobId: 'abnb-lead-601',
    title: 'Staff UI/UX Design Technologist & Frontend Lead',
    company: 'Airbnb',
    companyLogo: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=100&auto=format&fit=crop&q=60',
    companyDomain: 'airbnb.com',
    location: 'Remote',
    description: 'Bridge the world of high-craft design and cutting-edge frontend engineering. You will architect Airbnb next-gen design token engine and fluid micro-interaction systems.',
    requirements: [
      '6+ years blending deep CSS architecture, React, and motion engineering (Framer Motion / CSS animations)',
      'Track record building enterprise-grade accessible component libraries (WCAG AAA compliant)',
      'Exceptional taste in visual design, micro-copy, typography, and UX flow',
    ],
    benefits: [
      '$2,000 annual Airbnb travel credit to explore the world',
      'Top-quartile equity grants and competitive USD base',
      'Comprehensive family healthcare & mental wellness programs',
    ],
    salaryMin: 4800000,
    salaryMax: 7200000,
    currency: 'INR',
    employmentType: 'full-time',
    remoteType: 'remote',
    skills: ['React', 'TypeScript', 'Tailwind CSS', 'CSS', 'Framer Motion', 'Design Systems', 'UI/UX'],
    experienceLevel: 'Lead',
    postedAt: daysAgo(6),
    applyUrl: 'https://careers.airbnb.com/positions/design-technologist',
    applicationType: 'direct',
    isActive: true,
  },
  {
    id: 'job_duplicate_01',
    source: 'adzuna',
    sourceJobId: 'adz-dup-rzp-88',
    title: 'Sr React Native Engineer (Checkout)',
    company: 'Razorpay',
    companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=60',
    companyDomain: 'razorpay.com',
    location: 'Ahmedabad, India',
    description: 'We are looking for a Senior React Native Engineer to lead the mobile checkout experience for merchants. Design, build, and optimize high-throughput mobile payment flows.',
    requirements: [
      '4+ years of professional software engineering with React Native',
      'Strong proficiency in TypeScript, Redux, and mobile performance',
    ],
    salaryMin: 1800000,
    salaryMax: 2700000,
    currency: 'INR',
    employmentType: 'full-time',
    remoteType: 'hybrid',
    skills: ['React Native', 'TypeScript', 'Redux', 'Mobile Performance'],
    experienceLevel: 'Senior',
    postedAt: hoursAgo(4),
    applyUrl: 'https://www.adzuna.in/land/ad/razorpay-rn-senior',
    applicationType: 'external',
    isActive: true,
  },
];
